spring:
  application:
    name: gateway-service # 服务名称

  cloud:
    gateway:
      discovery:
        enabled: true #启用自动根据服务ID生成路由
        lower-case-service-id: true # 设置路由的路径为小写的服务ID
      routes:
        - id: consumer-client
          uri: lb://consumer-client #eureka注册中心存在的服务名称
          predicates:
            - Path=/api/** #路径配置
          filters:
            - StripPrefix=1     #忽略Path配置的个数，此处为1代表访问/api/customer/**时，会将api忽略，真实的访问地址为lb://admin-api/customer/**,如果为2，则为lb://admin-api/**

        - id: test_www
          uri: https://www.baidu.com/
          predicates:
            - Path=/ss/**

server:
  port: 10215 # 服务端口

# 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10211/eureka/
  instance:
    prefer-ip-address: true
