spring:
  application:
    name: provider-client

#服务端口
server:
  port: 10213

# 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10211/eureka/
  instance:
    prefer-ip-address: true
